# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: becdcf2cf8c9c1b2b406375bfb5f237e6c22b11882ab0c864567a92d48fcd8eb943640e80ca88b972387f210fb25b7bf43458a4972b5016efbc641fe498c91a2

test:
  secret_key_base: 9c51eb2c66f1666edc34554c19ecec24084359913ae07edda31c49c78d0266aa3684c10f27e2567cbc2881d8bdef51805b2a701f12817ec0fe19c2046731f5dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
